### ISSUE TITLE
Operation Id field too short

### ISSUE THREAD

**Issue by harveybc** [bjdash/apic#10]
In the API designer, when editing an endpoint, in the Operation Id field , a string lilke "controlllers.authorization.create" wont fit. It would be more confortable to use if this field has at least double the current length, so i can make even more organizated actions for my endpoints in deep folders, like "controllers.autorization.create.create".

PD: Your application is amazing! have no words. Unbelievable that is made by one man, Congrats.

**Comment by bjdash** [comment]
Thanks for the kind words and logging the issue.
I will increase the length of Operation Id and push a new build in a day or two.

Cheers.

**Comment by harveybc** [comment]
Works perfectly now. Thanks man!
