### ISSUE TITLE
No field to configure  x-basicInfoFunc for basic authentication

### ISSUE THREAD

**Issue by harveybc** [bjdash/apic#11]
When i configure basic auth, can't find a field in the api designer/endpoints screen to configure x-basicInfoFunc to specify the function to use to perform the basic authentication (similar to Operation Id for endpoints), for example i have to add everytime manually to the yaml the following line, at the same indentation level than securityDefinitions:basic_auth:type:

x-basicInfoFunc: controllers.authentication.basic_auth.authenticate

Maybe a new field for this is convenient in the api designer/endpoints screen, just under the security field.

Again, ty for the program, it saved me lots of time. 

PD: I couldnt find the landing page by googling: "apic", maybe some tweaks in the landing page make easier to find it by google.

**Comment by bjdash** [comment]
Thanks for the SEO suggestion. I am currently working on migrating this app from AngularJS to Angular. Will definitely consider SEO. 

Regarding x-basicInfoFunc, I will add option to define x- properties in API designer in next few days.

**Comment by harveybc** [comment]
Working perfectly, ty.
