### ISSUE TITLE
 Spoiled ver 3.0.2 Chrome Extension

### ISSUE THREAD

**Issue by AleksCerberus** [bjdash/apic#23]
Chrome Extension ver 3.0.2
Chrome 93.0.4577.63 (Official build), (x86_64)

<img width="1582" alt="Снимок экрана 2021-09-07 в 21 36 52" src="https://user-images.githubusercontent.com/22369348/132395720-7e41e193-f714-4404-8c3a-ad2494afbff1.png">

<img width="453" alt="Снимок экрана 2021-09-07 в 21 45 51" src="https://user-images.githubusercontent.com/22369348/132395750-f4c54758-1477-4f0a-84a0-044ae3b69859.png">

**Comment by bjdash** [comment]
This is happening after upgrading to angular 12 which is adding where angular is adding inline scripts to the generated index.html file. [See this bug](https://github.com/angular/angular-cli/issues/20864). A new build with the fix has been uploaded and should be available soon after reviewed by chrome extension team.

**Comment by bjdash** [comment]
New version is now available in chrome store.
