### ISSUE TITLE
"Deprecated" endpoint looks available in Docs by Tag

### ISSUE THREAD

**Issue by AleksCerberus** [bjdash/apic#24]
Steps to reproduce:
1) Create Endpoint
2) Mark Endpoint as Deprecated
3) Switch to Docs tab
4) Select "Group APIs by" as URL - marked as Deprecated as expected
<img width="660" alt="Снимок экрана 2021-09-07 в 22 13 06" src="https://user-images.githubusercontent.com/22369348/132398841-4cc7f1d3-050c-42c2-b06b-e03e62496a92.png">

5) Select "Group APIs by" as Tags - **not** marked as Deprecated
<img width="597" alt="Снимок экрана 2021-09-07 в 22 13 12" src="https://user-images.githubusercontent.com/22369348/132398956-64d6b9c8-95c9-442b-b73d-cff7a370e414.png">

**Comment by bjdash** [comment]
This has been addressed in the latest release [3.0.4](https://github.com/bjdash/apic/releases)
