### ISSUE TITLE
Tabs "API Designer" and "Docs" not sync ver 3.0.2 Mac

### ISSUE THREAD

**Issue by AleksCerberus** [bjdash/apic#25]
Steps to reproduce:
1) Open App on Mac
2) Switch to  API Designer tab
3) Open project (ex. Project_1)
4) Switch to Docs tab - opens Docs for Project_1
5) Switch to  API Designer tab
6) Open other project (ex. Project_2)
7) Switch to Docs tab - still opens Docs for Project_1 from step 4)
8) Open other project on Docs tab (ex. Project_3)
9) Select API Designer tab - still opens Project_2 from step 6)

**Comment by AleksCerberus** [comment]
If step 4. Replace by clicking button "View Docs" then Docs tab opens in sync with opened Project in API Designer tab.
But we do not have option to open API Designer tab in sync from Docs tab. There is no similar button

**Comment by bjdash** [comment]
Hmm, interesting idea. I never thought of syncing the designer and docs sections. They were always considered independent screens and each section remembers the last item you have opened. Thats why if you are on Docs:Project_1 and move to Designer: Project_2, when you come back to docs you still see Project_1 as it was the last item opened in docs page. The rationale behind this was a user might want to view the last item they were working on when they come back to the page.

I am planning to redesign the docs page as it's pretty basic. Will consider this scenario during the redesign.

**Comment by bjdash** [comment]
You can now jump to the designer section for a project right from the docs window by clicking on the `Edit` button in the left menu.
![image](https://user-images.githubusercontent.com/4252908/133059405-cfd10d76-5c9f-424d-9652-0214457ec5c6.png)
